#!/usr/bin/env node
/**
 * Generate the DSH bundle manifest from the skill itself.
 *
 * Nothing about Riffkit is written by hand in this repo. The workflow pulls
 * SKILL.md / HEARTBEAT.md / SKILL.json from riffkit.ai (the single source of
 * truth, served from the app on deploy) and this script derives package.json +
 * cordis.patch.yml from them. Change the skill's name, description or version
 * upstream and the package follows on the next run — there is no second copy
 * of those facts to keep in sync.
 *
 * What is hand-maintained here is only DSH's *shape*: the `dsh.bundle.patch`
 * pointer and the patch row below. Those change when DSH changes its packaging
 * contract, not when we change the skill.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const PKG_NAME = '@riffkit/dsh-plugin'
const SKILL_DIR_NAME = 'riffkit' // <root>/<name>/SKILL.md — discovery is one level deep

const skillJson = JSON.parse(readFileSync(join(ROOT, 'SKILL.json'), 'utf8'))
const skillMd = readFileSync(join(ROOT, 'skills', SKILL_DIR_NAME, 'SKILL.md'), 'utf8')

// Frontmatter is the skill's own metadata block; take description from there so
// the npm listing says exactly what the skill says about itself.
const fm = skillMd.match(/^---\n([\s\S]*?)\n---/)
if (!fm) throw new Error('SKILL.md has no frontmatter — refusing to guess')
const field = (key) => {
  const m = fm[1].match(new RegExp(`^${key}:\\s*(?:"([^"]*)"|'([^']*)'|(.*))$`, 'm'))
  return m ? (m[1] ?? m[2] ?? m[3]).trim() : null
}

const version = skillJson.version
if (!/^\d+\.\d+\.\d+$/.test(version)) throw new Error(`SKILL.json version is not semver: ${version}`)

// The skill's own description doubles as the agent's trigger list ("Triggers:
// the user says …"), which is exactly right in frontmatter and wrong on an npm
// listing page. Keep the part that describes the thing, drop the trigger half,
// and collapse the wrapped lines.
const prose = (field('description') || '')
  .split(/\s*Triggers:/i)[0]
  .replace(/\\n/g, ' ')
  .replace(/\s+/g, ' ')
  .trim()
// Cut on a sentence boundary, never mid-word: an npm card that trails off in
// the middle of a word reads as broken tooling.
let description = ''
for (const sentence of prose.split(/(?<=\.)\s+/)) {
  if (description && (description + ' ' + sentence).length > 300) break
  description = description ? `${description} ${sentence}` : sentence
}
description = description.trim()
  || 'Riff a winning short video into your own — the formula, not the footage.'

writeFileSync(join(ROOT, 'package.json'), JSON.stringify({
  name: PKG_NAME,
  version,
  description,
  license: 'MIT',
  homepage: 'https://riffkit.ai',
  repository: { type: 'git', url: 'git+https://github.com/riffkit/dsh-plugin.git' },
  keywords: ['dsh', 'deepseek-harness', 'skill', 'tiktok', 'video', 'ai-video', 'riffkit'],
  // Ship ONLY the patch and the skill tree. Without both, the installed package
  // has nothing for the patch to point at.
  files: ['cordis.patch.yml', 'skills'],
  // The one field DSH itself reads (apps/cli/src/plugin.ts::exportsPatch). A
  // package without it still installs, but contributes no layer and DSH prints
  // a warning instead.
  dsh: { bundle: { patch: './cordis.patch.yml' } },
}, null, 2) + '\n')

// The patch INSERTS its own provider row rather than overriding the base
// `skill-filesystem` one: a patch replaces the targeted row's whole `config`
// instead of merging into it, so overriding would silently wipe whatever the
// user (or the base bundle) had configured there.
//
// `includeDefaultRoots: false` keeps this provider looking at exactly one root —
// our own directory inside the installed package — so it can neither shadow nor
// be shadowed by the user's own skills.
//
// The !!js expression is evaluated by cordis inside `with (ctx)`, where
// `baseUrl` is a Context property; `createRequire(baseUrl).resolve(...)` is how
// the package locates its own installed directory (there is no __dirname here).
writeFileSync(join(ROOT, 'cordis.patch.yml'),
`# Generated by scripts/generate.mjs — do not edit by hand.
- insert:
    - id: riffkit-skill-root
      name: '@deepseek-ai/dsh-skill-filesystem'
      config:
        providerName: riffkit-bundle
        includeDefaultRoots: false
        watch: false
        customSkillDirs:
          - !!js "process.getBuiltinModule('node:path').join(process.getBuiltinModule('node:module').createRequire(baseUrl).resolve('${PKG_NAME}/package.json'), '..', 'skills')"
`)

console.log(`generated package.json + cordis.patch.yml for ${PKG_NAME}@${version}`)
